import numpy as np

if __name__ == "__main__":
    a = np.zeros(10)
    a[4] = 1
    print(a)
    print(np.arange(10, 100, 1))
    print(np.arange(9).reshape(3, 3))
    print(np.nonzero([1, 2, 0, 0, 4, 0]))
    print(np.eye(4))
    a = np.random.random((10, 10))
    print(a)
    min, max = np.min(a), np.max(a)
    print(min, max)
    print(np.tile(np.array([[0, 1], [1, 0]]), (4, 4)))
    Z = np.random.random((5, 5))
    min, max = np.min(Z), np.max(Z)
    # min max normalization
    Z = (Z - min) / (max - min)
    A = np.arange(15).reshape(5, 3)
    B = np.arange(6).reshape(3, 2)
    print("---------------------------")
    print(A, B, np.dot(A, B), A.dot(B))
    a = np.arange(10)
    print(np.tile(a, (10, 1)))
    print("---------------------------")
    Z = np.zeros((10, 10))
    print(Z)
    Z += np.arange(10)
    print(Z)
    print(np.linspace(0, 1, 1002)[1:-1])
    a = np.random.random((100))
    np.sort(a)
    print("---------------------------")
    A = np.random.randint(0, 2, (2, 2))
    B = np.random.randint(0, 2, (2, 2))
    print(np.allclose(A, B))
    Z = np.random.random(1000)
    print(Z.mean())
    print(np.mean(Z))

    Z = np.random.random((100, 2))
    X, Y = Z[:, 0], Z[:, 1]
    print(np.sqrt(X**2 + Y**2))
    print(np.arctan2(Y, X))
